name: microwave-remote-sensing
channels:
  - conda-forge
dependencies:
  - aiohttp
  - cmcrameri
  - dask
  - datashader
  - folium
  - graphviz
  - hvplot
  - intake
  - intake-xarray
  - jupyter
  - jupyter-cache
  - jupyter_bokeh
  - mamba
  - matplotlib
  - nodejs
  - odc-stac
  - pandas-stubs>=2.3.2.250926
  - pip
  - pre-commit
  - pydantic>=2.12.2
  - pydantic-extra-types>=2.10.6
  - pyproj
  - pystac-client
  - python-gitlab
  - python<3.14,>=3.12
  - requests
  - rich
  - rioxarray
  - scikit-image
  - scipy
  - seaborn
  - snaphu
  - xarray
  - zarr=2.18.4
  - pip:
      - .
